substitutions:
  # device config
  device_name: portal-dev
  platform: ESP32
  board: nodemcu-32s

  # cover config
  open_duration: "30000" # ms
  close_duration: "30000" # ms
  cover_device_class: garage

  # switch config
  cover_switch_pin: GPIO2 # gpio pin that trigger the door opening/closing/stop
  active_switch_duration: 100ms # amount of time relay is closed
  $push_interval: "1500" # safe time between relay activations in ms

  # endstop config
  open_endstop_pin: GPIO5 # gpio pin for open endstop sensor
  close_endstop_pin: GPIO19 # gpio pin for close endstop sensor
  debounce_time: 30ms # debounce time for open/close endstops

packages:
  common: !include common/config_base.yaml
  wifi: !include common/wifi_base.yaml
  device_base: !include common/cover_base.yaml


# Enable logging
logger:
  level: INFO
  # level: DEBUG

# Example of an external switch to command the door
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    name: Cover Button
    id: cover_button
    internal: true
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            auto custom_door = static_cast<CustomGarageCover *>(id(garage_door));
            // external switch pressed
            custom_door->activate_door();
