# add your board config
esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

substitutions:
  # device config
  device_name: sc-example
  cover_id: sc_cover_example

  # cover config
  open_duration: 30s # seconds
  close_duration: 30s # seconds
  cover_device_class: garage

  # switch config
  cover_switch_pin: GPIO17 # gpio pin that triggers the door opening/closing/stop
  active_switch_duration: 100ms # amount of time relay is closed
  switch_interval: 1500ms # time between switch activations

  # endstop config
  open_endstop_pin: GPIO18 # gpio pin for open endstop sensor
  close_endstop_pin: GPIO19 # gpio pin for close endstop sensor
  debounce_time: 100ms # debounce time for open/close endstops

  # setup config
  # If your endstops take a while to configure (eg with debounce)
  # Then you can set this.  If you do, it should be longer than
  # the debouce time, plus around 50ms.
  setup_delay: 200ms

esphome:
  name: $device_name

external_components:
  - source: github://juaigl/esphome-garage-cover-single-control@master

wifi:
  # replace by your own data
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret esphome_fallback_wifi_password

captive_portal:

api:
  encryption:
    # replace by your key
    key: !secret esphome_encryption_key

ota:
  # replace by your password
  - platform: esphome
    password: !secret esphome_api_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: $open_endstop_pin
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Open Endstop Sensor"
    id: open_endstop
    internal: true
    filters:
      - delayed_on_off: $debounce_time

  - platform: gpio
    pin:
      number: $close_endstop_pin
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Close Endstop Sensor"
    id: close_endstop
    internal: true
    filters:
      - delayed_on_off: $debounce_time

  # Example of an external switch/button to command the door
  - platform: gpio
    pin:
      number: GPIO22
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Cover External Button"
    id: cover_external_button
    internal: false
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - cover.toggle: $cover_id

output:
  - platform: gpio
    pin: $cover_switch_pin
    id: cover_switch

button:
  - platform: output
    name: "Cover Button"
    id: cover_button
    output: cover_switch
    duration: $active_switch_duration
    internal: true


cover:
  - platform: sc_cover
    name: $cover_id
    id: $cover_id
    device_class: $cover_device_class
    door_activate_button: cover_button
    setup_delay: $setup_delay
    open_endstop: open_endstop
    close_endstop: close_endstop
    button_press_interval: $switch_interval
    open_duration: $open_duration
    close_duration: $close_duration
