wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret esphome_fallback_wifi_password

captive_portal:

# Enable Home Assistant API
api:
  password: !secret esphome_api_ota_password

ota:
  password: !secret esphome_api_ota_password
