esphome:
  name: $device_name
  platform: $platform
  board: $board
  includes:
    - common/cover_base.h

binary_sensor:
  - platform: gpio
    pin:
      number: $open_endstop_pin
      mode: INPUT_PULLUP
      inverted: true
    name: "Open Endstop Sensor"
    id: open_endstop
    internal: true
    filters:
      - delayed_on_off: $debounce_time
    on_press:
      then:
        - lambda: |-
            auto custom_door = static_cast<CustomGarageCover *>(id(garage_door));
            // notify sensor endstop reached
            custom_door->open_endstop_reached();
    on_release:
      # door was commanded manually (not esphome)
      then:
        - lambda: |-
            auto custom_door = static_cast<CustomGarageCover *>(id(garage_door));
            // notify sensor endstop released
            custom_door->open_endstop_released();

  - platform: gpio
    pin:
      number: $close_endstop_pin
      mode: INPUT_PULLUP
      inverted: true
    name: "Close Endstop Sensor"
    id: close_endstop
    internal: true
    filters:
      - delayed_on_off: $debounce_time
    on_press:
      then:
        - lambda: |-
            auto custom_door = static_cast<CustomGarageCover *>(id(garage_door));
            // notify sensor endstop reached
            custom_door->close_endstop_reached();
    on_release:
      # door was commanded manually (not esphome)
      then:
        - lambda: |-
            auto custom_door = static_cast<CustomGarageCover *>(id(garage_door));
            // notify sensor endstop released
            custom_door->close_endstop_released();

switch:
  - platform: gpio
    pin: $cover_switch_pin
    name: "Cover Switch"
    id: cover_switch
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: $active_switch_duration
      - switch.turn_off: cover_switch

cover:
  - platform: custom
    lambda: |-
      auto my_cover = new CustomGarageCover(id(cover_switch), id(open_endstop), id(close_endstop));
      my_cover->set_door_timings($push_interval, $open_duration, $close_duration);
      App.register_component(my_cover);
      return {my_cover};

    covers:
      - name: $device_name
        id: garage_door
        device_class: $cover_device_class
